---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBhWPagBYhQ83lBbR8ZjQ2s1Rw0su6WQErzFG3tg9NdOVReHRgReQWLWWQFCP33eNhI6kfUEefBBrRybG8BvoI3CCnHHB+PzQn1UT1CFzrbk1HZJwmqC19SolHFL1flFATTW6WFxDNcfG8nsD6dJKc0Q/uOMfJ78PFG8kM+Ru0cqmE+fdgYEcw17//pCreK7JL6jH18E+50Aj/Sa8qF86zKBYK5Z1WiOBtQYZUO42GUblU5GBqnBv+BJkm36mMVDQ7PB2QafCWm1DYLX9LaNk1hzGCd6P0ycvQSu5I1CPPVEPiJ+v4FDgixsnAFrJJ3SbUkm/lHq+LvGuq/a4s4tR1KTlW+kmGhRzjsCb+dYPYyqmsxHds32GiDud+ACHGo7eWMPvHKQMTwejKjmLlQ0011N8EPOo9kxx8COLTUMwZeuy7uwBm8QRYsZXRXqHcbOpyZt8ZmYC2ZcUZXZbS8dPMW9LHU1uN7AUPW0efjdiTVi37ZcnyDC4ddDe9dOPB1qVaH1GKAK2q6ohrEDTCJc6faxp+YAWlFyZwXI7WzvdZNpvUvIrqcdDEcnD8XmUGRyY2CUZXddzfHkFTLdcY5EN1eeAQjWh79ZGBTnjM/S0WWX34cpdoikRIXQRvK5Bgy6l1g/cP1Vi69EPOhWflpfKF0KRG3IkxeZcy6OOW/w2Cjo25TxxfUoEG9PPjhoYSkCMGFIdIy7Xwjyv4HgeQT5q7BluXtwacIsAWSCspPXyQf+Q==
    admin-user: AgATO/gGHalBEzXcOrO/qgGQcEl+3bmlegUOqshf70lCVTlKByRKHKX/clWSy8fmGXzVDxwIsDCwJx0V4O9uaJxbDPOivTdosgeKiouhJwWBt0oHQ+tdeG6ZLOkiT7r3An1g74uGfw5m8ml2YIGEQYR8rv383nldyoX/ZmUB9xgN9gOHYTl0vLIWdrlsos1bUtIipPMuDruHcEh6itMBmFSKQ5MeGNmEUp11sogTACrP+I92/tw/dpzanY+mco2NY02hTTv2n1cFH+/tpBrA18ep1pk/9GNyrOprBc4aLSWUIkDRU5zAv4QboOhcA5/VxJKuQ4hPNsHeHfqgQ2TpI2yTiJK23YLDe5P2/UCauKr7VqyZTZO0wKiD7TsM5obiB4jvi0xpgw1XddnegRE/XHxrr10rwKzsI80fC5a11O7zXOq6WyKEowTGOS96U+Ju2NCy9Pq7Ts04U38UvZCC+LnlVZFoQFm82X7yS2BvU9+/2MqiyeG0Yo+lNNfuZMHQlUDkyIrbewX8MBXlGcWYAldCu2mEcBQ854ZjvuMdfOv7w4AO3ITZohnGXoaA5gbZuYHKqtgADgCWvHScVGPV4Gs+BcmnkvmkL50KVfiJlSqAPURRBv+x1+ZBYzuHDU6ccofsNc9E4xO0ihwihNuDcACWJXrgEhxqOw8M6X0eFXqbnFCgvN5Mbjb7dBC7BMK4ZREFApYzkQ==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
