---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgChjxve0+iFGv//m5znkxzFA/jJTQ5GP+HVQ8L9DD5wM7mKg3055LNZl5PnG4iXSyOpF+LGgoHlY/eNBv2tvH8dOcnZ4gXTL7sY5LsnUqZYoVaZniEulKlexB53z+FKjSwVN40Qg6q1RrXjZPsgZid4hHmCyckIfka4bfclcLqVbINVIh9TPMjxPyqUq5+l1QLGC1fAXtaCMx33vPYe1HzUVXo64BsIOf/pV93ZDLBKbLTHA1qIjDL4Usd0VJv+Wtpd/PaEZM4CY0VF5qA0be6XuN0z4/NmuZyh6dnMgrc7q8K0NxdWLV4ZrEJPTCE7Hgc+QpHoXmRjryfUOxRfud67ZP9D/dSQBRhF6wdDGmjsH8YDHkvVjuEuY4gL8Tymxdx97XGm2NrDC3dHj5Uc+622MhrxBV3yc6jsG0/sEV79EN/SkrT7jzBG1xru4UV59H0Sv/pT4xKCnk2S5Is7iJ/cU++KRXX2ehlLeJjHmpARLD17VQzLuAqPtB7qS3jEPyBPPugg9A6vKajRSIAdU9qzZ9L0PMUHbcJKtHVRnybIKil3Jx/VbaiJhCBC+zD0XLM+n60osGt4lXDS8RntcjBy5Jpe1SulvR3egtvp4ZB71CnPnqmO95mRW6c+H2uHBzWJGRj9Sx/lHpAxiFoRnyzinLtlv5DYXfpTEd0hZIbQro6ZvYNCa81Ur8+8Sv9MsKkuwOqHZBELe5lSUNKxjlmE62cc3SbSvWih6P/A4FGhag==
    admin-user: AgBgqjtMP65lrZU3K+JYCgYReCvW+AB/qeRT48iHR9niKXGjedWCizS9/2hPD79Yc6C8OIoQSZ4PYjpX7a+CyXlayL7Dq8a8mkaiUqoPvTB9DJI4wg7kQ1LHEZx0VQx0YButcNjdXHF8gx8OZM5ilH4thGDmglnzHdz/xazTuRSmzP4plB+16jtHVv/yoR7DJazksy0sVUktjxZ7hIhxr4DC4QxaUHGOBVDKer2+ISVyh5e9T8DAbe8WQWq8ERvcYJLp9HUePKFVl7udLpdjYCkwzInnZwlc+D2k2cBkbLHDSDvZnQMnWn1pzRK8tbtMLQOZHwHub9uJEzv6imYxiacSw5LYN8z0YAiIIY0ooesV8M+nqn2P4s4Y9CCrOFJk/NAijiMgCK1c8IlAtKWZQjco/r7ZcjKs9pV7cQOG8Hro3BrxdzPGyXeOpfD4V5gID6HxX5HdQ7jf6rdkMtiQHPfMX58Ak8BkjG4f5Gfq2jL4JXFFAedKuVZQrP5+5o4fLrdgGWs6UFOpktWsbw5rsMnkj7tEnyNLdio91h6rqcOB1FJMyHfKacc2jXRXUfr37GnwosScKRoEedzVLRPEr3XjDSoC/8gvNaYBg6L8glTJXC38NXnbvJDo3bI/VwtM6Sero/6oInlJJEUz4b4w/iG7oArHjJmilaN8eaa+eoq5GqrkbxRzIzNv82tajh3VUPnjQxybpA==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
