---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: my-database-secret
  namespace: default
spec:
  encryptedData:
    database-password: AgDAHoeKpYkhvCIEvM1t76f/nViEJ6/czq8W7hFx9cUANb0p668H+UvMx3vPLH7ls2LjqyBsTIQtg26SOhLTXuhd2Jl52OuRRFp7R5XFU6VDYEy6muCSH79iaiHVETZT7fJw7/Vw56PMYoyGO1wCYXbvog/7GZSKutUOpzL0i95UbRn2zIUuFzb6ZCPIC1wjOEk25wd2yWHJTvLeJ24gJI7oA/4bLX6+MoPeYKRvIlwJaElxOiqIIr0Dn6EkeUbhTgTi8thqpUsb/pKBZaLk2yyMEVKTb1a1rZeERYRITeA2PNneUbudUkNTLd8tVykFBS6qne9iqwwbJPISXTck6Fqfqp9ButbJ13WudpyDWKBUATE3mIPOlYOD4bQA/PQ0Mz0UCCr4BzcNtK++S875ZVFmPe/v3Vuglqph2rSCvMKdkGisWlnZPtX6YyI2jmhPC22AEymcgLMLAvpqY+vrp8eOIC1869Tw3Jpop4wxzbtNKpvUZZ6XiFrc1sjy3J2gR6owgkTR8I70c39FZw395fT0qx55Wuw7PEt1010Ej3XO0bHHfeVMY+eDIP3evZddB6QATu5IZ9fC07Fh0yuP/vFfCC7q/6L8ZXQjMUyk3CtlOYSeVHet/A5NEPDKscSrsMotrJqFvVLeumnbLjmmqDEddRUTu5ODb33xRZmXgrHVg1nc92GGhzJg3OrE/1eDc9SQ10gPbPHaOZlCIx7+zOe8sPZkubsA+kAZ
  template:
    metadata:
      name: my-database-secret
      namespace: default
    type: Opaque
