---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAQeiHANBBZ/L1g6DDWPUvVuCrxHgsOnu3jmFC6CtaVgH1+8JotL1ybN7PSsLOibx7Ux4Jhhgj4AWrarX63qsEjJzL0YnCooWrIyGYM/J3HLu3Yw0DiDxWBuAN/ZCQ8IAseCA/HFP1m3DVMBad1QTWQyQ7g2f3plKMGBQE8dGHmXMOMk8Em2DvAlX0fyWQJmZK67lw9vaghclSsLJa/Si+odLOYW6+oikFlNXuMbwrHH2Lw+kPGwLvkVszQMpUnNyASkEO9g3tUKGYWKg61j7wGoscFrsdkGY29y+hu5xs3o6YoEKZkPtmaqepp0npSLPRAWOwrE/Rukv4zFlcW5r+1eon2N6p5Sx6dkBTNxAAwrjmtsl/srzZNKmZbP0cWz9L4D0XKAorNxlpZyrwAt0xKcrUCGBj/m2hXToABAfvlhwPYC9OhtuUxzFiI7XEaNya55iQ6HVGjMnVKAyKmUVJixz8GFNuQb5D1bHMmT3OWltXNux2JkzMJayBuxdCR+CY8TEmiNBSshunZe8cPM4kZBfpGXWi2124lDeSFuJMblUro37njBI7nrVh0zcjYHLwO+x8pJpamdNsNUFgzGrZtxn90giwTUxStMJ+x4TS+uxRaJhoqWYQDLD42IdfGpFFhx6j/pR0J4Ip+Bc2JLscPOXqh0YyInV7OfkOW6MV6RKPhbBOZ1Zd0kJ3PbKeCvTsaeJFmlsFEf67h10R+0iK5p5RJ3DJC/5SMnaOzmb/NLQ==
    admin-user: AgCAO2FTZvx165qGEjEL0t+aE4BMibCBaeSnVFlGx5LtLgtnFBTLzFHvBd/ZhHanWVIyQH8AmMeWgRk/ZK5tx7tXmz7DTu23J7gjb9Ams2hHrsYa3PvTlR4hP/9U8+5OBaJ2KP9HPgzOTwJB3DTY0HusUoYWizesXKVURhVKc7OVGS75yiLH1T22pAXbZcF4NjeuOc3uOmE6JHvV2mMgP7Jl4vyi5rm6lzWAN0uru13Yj/Z11iSwW9Gxj9Wiul9Br5RDNWgg0Tl7ad+vaK8F/VsOBvJee95zAZ+PwVY1z6dkS7LBfAFnlKzlm+fnEDXa42v8KDsf6l7vxY5/NlrbThttep2F7Yhu7c4roIeocHnk3Qq0uOyE1FaxcJxmBYKvD5upuUKgka+9Aw20zWp+6phDJ6vZfKzn1gmSIe0D8idW9tnlUrsugl+QxCKie8Cy3ilxS5qYzmL0rlKW83k05eb0x4nhRwIyHAtRA40OqKte69egizBxvYRexct/FXzWJgFZdq2QlEDmxg90/+XuFESQ5zdjXgJaCoVIvJ53CAZJTpL66nEa7Tr2MRfpYA46wc6um8e0QeygnHGs5mCHWy0QZ8A7coY1x7Cx+e3Q6JoEJI8zRGWB5Pxs8tU0dGEcavCsPIA3Z1AzX9mIjLjP5ekcFtNZMvLnV3I13OYZJ1Olxe0g0rAyu5WvuGM/n3Phxrk5UEG8bw==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
